apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-deployment
spec:
  selector:
    matchLabels:
      app: collection
  template:
    metadata:
      labels:
        app: collection
    spec:
      containers:
      - name: collection
        image: /collection:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDb__Host
            value: mongodb-service
          - name: MongoDb__Password
            valueFrom:
              secretKeyRef:
                name: collection-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: health/live
            port: 80
        readinessProbe:
          httpGet:
            path: health/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: collection-service
spec:
  type: LoadBalancer
  selector:
    app: collection
  ports:
    - port: 80
      targetPort: 80

